name: Publish Vagrant Box

on:  
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v3

      - name: Get the version from the git tag
        uses: olegtarasov/get-tag@v2.1
        with:
          tagRegex: "v(.*)"

      - name: Build box
        run: |
          packer build --only=virtualbox-iso nixos-x86_64.json

      - name: Publish box to Vagrant Cloud
        run: |
          vagrant cloud publish insilica/sysrev-dev ${{ env.GIT_TAG_NAME }} virtualbox nixos-21.05-virtualbox-x86_64.box --no-tty
        env:
          ATLAS_TOKEN: ${{ secrets.ATLAS_TOKEN }}